#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: fasta-nfs-pvc
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      # This doesn't really matter for a static PV
#      storage: 10Gi
#  volumeMode: Filesystem
#  volumeName: fasta-nfs-pv
#  storageClassName: fasta-sc
#  selector:
#    matchLabels:
#      app: "fasta"