---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fasta-slib2-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # This doesn't really matter for a static PV
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: fasta-slib2-pv
  storageClassName: csi-cephfs-sc
#  selector:
#    matchLabels:
#      app: "fasta"