#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: fasta-cephfs-pvc
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      # This doesn't really matter for a static PV
#      storage: 1Gi
#  volumeMode: Filesystem
#  volumeName: fasta-cephfs-pv
#  storageClassName: csi-cephfs-sc
#  selector:
#    matchLabels:
#      app: "fasta"